/*
 * generated by Xtext 2.12.0
 */
package projetoCompiladores


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PascalStandaloneSetup extends PascalStandaloneSetupGenerated {

	def static void doSetup() {
		new PascalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
